### ISSUE TITLE
Error message when pre-rendering

### ISSUE THREAD

**Issue by PoiScript** [PoiScript/solomon#42]
```
Saving "/post/introducing-solomon" as "/home/poi/projects/solomon/dist/post/introducing-solomon/index.html"
ERROR TypeError: Cannot read property 'length' of undefined
    at Object.updateRenderer (/home/poi/projects/solomon/dist/dist-server/main.bundle.js:1:144530)
    at Object.updateRenderer (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12791:70)
    at checkAndUpdateView (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12307:14)
    at callViewAction (/home/poi/projects/solomon/packages/core/src/view/view.ts:782:1)
    at execComponentViewsAction (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12602:13)
    at checkAndUpdateView (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12308:5)
    at callViewAction (/home/poi/projects/solomon/packages/core/src/view/view.ts:782:1)
    at execComponentViewsAction (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12602:13)
    at checkAndUpdateView (/home/poi/projects/solomon/node_modules/@angular/core/bundles/core.umd.js:12308:5)
    at callViewAction (/home/poi/projects/solomon/packages/core/src/view/view.ts:782:1)
```

After checking Travis-CI build history, this error first occurs in commit  5de7079792f035f04798c24ebd2e8d09139e1774.

**Comment by PoiScript** [comment]
As far as I'm concerned, the problem is that some posts doesn't have any comment so the api will return a empty array.
I'm working on the other issue #45. When it's done, the comment request will be ignored in server side and this issue should be gone with the wind as well.

**Comment by PoiScript** [comment]
I think I had located the error:
```html
<mat-form-field class="comment-textarea">
  <textarea matInput #content placeholder="Join the discussion" maxlength="500" [disabled]="!user"></textarea>
</mat-form-field>
```
After removing the `[disabled]="!user"`, the error changed to:
```
ERROR TypeError: Cannot read property 'display' of undefined
    at cloakElement (/home/poi/projects/solomon/node_modules/@angular/animations/bundles/animations-browser.umd.js:4551:51)
    at /home/poi/projects/solomon/packages/animations/browser/src/render/transition_animation_engine.ts:1797:1
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/poi/projects/solomon/packages/animations/browser/src/render/transition_animation_engine.ts:1797:1)
    at TransitionAnimationEngine._flushAnimations (/home/poi/projects/solomon/packages/animations/browser/src/render/transition_animation_engine.ts:1171:1)
    at TransitionAnimationEngine.flush (/home/poi/projects/solomon/packages/animations/browser/src/render/transition_animation_engine.ts:942:1)
    at InjectableAnimationEngine.AnimationEngine.flush (/home/poi/projects/solomon/node_modules/@angular/animations/bundles/animations-browser.umd.js:4861:32)
    at /home/poi/projects/solomon/packages/platform-browser/animations/src/animation_renderer.ts:134:1
    at ZoneDelegate.invoke (/home/poi/projects/solomon/node_modules/zone.js/dist/zone-node.js:392:26)
    at Zone.run (/home/poi/projects/solomon/node_modules/zone.js/dist/zone-node.js:142:43)
```
Then, I tried to removed the whole `<mat-form-field></mat-form-field>` and no error came out this time.

I found this issue https://github.com/angular/angular/issues/18562 similar to my error.

**Comment by PoiScript** [comment]
After upgrading to Angular 5.0 8653f24e90b55152bd826993ac36aa280b7c1c3d, the problem has been resolved.
